version: '3'

services:
  web:
    build: .
    env_file: .env
    container_name: web
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8000:8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app

  db:
    container_name: db
    restart: always
    networks:
      - net
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --character-set-server=utf8

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    networks:
      - net
    depends_on:
      - web
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./bdwms_blog/static:/opt/static
    ports:
      - "80:80"

  redis:
    image: redis:3.2
    restart: always
    volumes:
      - ./redis:/redis
    networks:
      - net

networks:
  net:
